// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/signin-variants/Glass.tsx": () => import("../components/mockups/signin-variants/Glass.tsx"),
  "./components/mockups/signin-variants/Immersive.tsx": () => import("../components/mockups/signin-variants/Immersive.tsx"),
  "./components/mockups/signin-variants/Split.tsx": () => import("../components/mockups/signin-variants/Split.tsx")
};
